create extension if not exists "uuid-ossp";
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, avatar_url text, language text not null default 'ne', theme text not null default 'light', daily_goal_minutes int not null default 30, target_wpm int not null default 30, role text not null default 'student', created_at timestamptz not null default now());
create table if not exists public.practice_sessions (id uuid primary key default uuid_generate_v4(), user_id uuid not null references public.profiles(id) on delete cascade, mode text not null, wpm int not null default 0, accuracy numeric(5,2) not null default 0, mistakes int not null default 0, typed_chars int not null default 0, duration_seconds int not null default 0, points int not null default 0, created_at timestamptz not null default now());
create table if not exists public.lessons (id uuid primary key default uuid_generate_v4(), title text not null, title_ne text, level int not null default 1, mode text not null, content text not null, difficulty text not null default 'beginner', xp int not null default 100, is_published boolean not null default true, created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.practice_sessions enable row level security; alter table public.lessons enable row level security;
create policy "Users can read own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Users can read own sessions" on public.practice_sessions for select using (auth.uid() = user_id);
create policy "Users can insert own sessions" on public.practice_sessions for insert with check (auth.uid() = user_id);
create policy "Published lessons readable" on public.lessons for select using (is_published = true);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, full_name, avatar_url) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email), new.raw_user_meta_data->>'avatar_url') on conflict (id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
