export const navItems = [
["dashboard","🏠","Dashboard | ड्यासबोर्ड"],["home","🏡","अभ्यास गृहकार्य\\nHome Practice"],["lessons","📚","पाठ (Lessons)\\nLessons"],["word","🔤","शब्द अभ्यास\\nWord Practice"],["sentence","🧾","वाक्य अभ्यास\\nSentence Practice"],["news","📰","समाचार अभ्यास\\nNews Practice"],["speed","⏱️","गति परीक्षा\\nSpeed Test"],["analytics","📊","नतिजा विश्लेषण\\nResults Analysis"],["leaderboard","🏆","लीडरबोर्ड\\nLeaderboard"],["settings","⚙️","सेटिङहरू\\nSettings"],["help","❔","सहायता / FAQ\\nHelp / FAQ"]];
export const stats = [
{title:"औसत गति (WPM)",value:"38",note:"▲ 6 आज",color:"purple",icon:"⏱️"},{title:"शुद्धता (Accuracy)",value:"93%",note:"▲ 3% आज",color:"green",icon:"🎯"},{title:"कुल अंक (Points)",value:"21,750",note:"▲ 1,200 आज",color:"orange",icon:"🏆"},{title:"लगातार अभ्यास (Streak)",value:"8 दिन",note:"सर्वोत्तम: 15 दिन",color:"red",icon:"🔥"}];
export const chartData=[{name:"Mon",wpm:28,accuracy:88,mistakes:58,time:45},{name:"Tue",wpm:38,accuracy:91,mistakes:42,time:75},{name:"Wed",wpm:22,accuracy:85,mistakes:34,time:52},{name:"Thu",wpm:33,accuracy:94,mistakes:24,time:62},{name:"Fri",wpm:31,accuracy:87,mistakes:18,time:78},{name:"Sat",wpm:24,accuracy:93,mistakes:16,time:65},{name:"Sun",wpm:36,accuracy:92,mistakes:14,time:88}];
export const leaders=[["1","प्रज्ञा भट्टराई","Pragya Bhattarai","23,560","68","95%","12 दिन"],["2","रोहन श्रेष्ठ","Rohan Shrestha","19,850","66","94%","10 दिन"],["3","विवेक पौडेल","Bibek Poudel","17,640","61","92%","8 दिन"],["4","समीक्षा अधिकारी","Samiksha Adhikari","16,230","58","90%","6 दिन"],["5","सागर अधिकारी","Sagar Achikari","11,250","52","93%","4 दिन"]];
export const lessons=[["Level 1","आधारभूत कुञ्जीहरू","Basic Keys",100,"✅"],["Level 2","नेपाली अक्षरहरू","Nepali Letters",72,"अ"],["Level 3","मात्राहरू","Matras",38,"ा"],["Level 4","शब्दहरू","Words",0,"📖"],["Level 5","वाक्यहरू","Sentences",0,"💬"],["Level 6","अनुच्छेदहरू","Paragraphs",0,"📄"],["Level 7","गति परीक्षा","Speed Test",0,"⏱️"],["Level 8","व्यावसायिक टाइपिङ परीक्षा","Professional Test",6,"👑"]];
export const preetiRows = [
[["`","~","symbol"],["1","!","symbol"],["2","@","symbol"],["3","#","symbol"],["4","$","symbol"],["5","%","symbol"],["6","^","symbol"],["7","&","symbol"],["8","*","symbol"],["9","(","symbol"],["0",")","symbol"],["-","_","symbol"],["=","+","symbol"],["Backspace","","wide"]],
[["Tab","","wide"],["फ","q","consonant"],["ू","w","matra"],["म","e","consonant"],["त","r","consonant"],["ज","t","consonant"],["ल","y","consonant"],["न","u","consonant"],["प","i","consonant"],["व","o","consonant"],["च","p","consonant"],["ख","[","consonant"],["ह","]","consonant"],["Enter","","wide"]],
[["Caps Lock","","wide"],["आ","a","vowel"],["स","s","consonant"],["द","d","consonant"],["ि","f","matra"],["ु","g","matra"],["ग","h","consonant"],["क","j","consonant"],[";","k","symbol"],[":","l","symbol"],["'",";","symbol"],["Shift","","wide"]],
[["Shift","","wide"],["य","z","consonant"],["र","x","consonant"],["ल","c","consonant"],["व","v","consonant"],["श","b","consonant"],["ष","n","consonant"],["स","m","consonant"],["ह",",","consonant"],["ज्ञ",".","consonant"],["।","/","symbol"],["Shift","","wide"]],
[["Ctrl","","wide"],["Win","","symbol"],["Alt","","wide"],["Space","","space"],["Alt","","wide"],["Ctrl","","wide"]]];
